name: Update images
on:
  push:
    branches: [ gh-pages, feat/load-images-via-github-actions ]
    # whenever card data is updated
    paths:
      - 'dist/data.min.js'
      - '.github/**'
jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.ref }}

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - run: pip install -r requirements.txt

      - name: Download Files
        uses: ./.github/actions/download-files
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Extract Assets
        uses: ./.github/actions/extract-assets
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Extract Images
        uses: ./.github/actions/extract-images
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Resize Images
        uses: ./.github/actions/resize-images
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Update Spritesheets
        uses: ./.github/actions/update-spritesheets
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Jon Senchyna'
          git config --global user.email 'TheSench@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto-update of Spellstone Images"
          git push
