name: Update images
on:
  push:
    branches: [ gh-pages ]
    # whenever card data is updated
    paths:
      - 'dist/data.min.js'
  pull_request:
    branches: [ gh-pages ]
jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
        env:
          AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: Create virtual environment
        run: |
          python3 -m venv venv

      - name: Download Files
        uses: ./.github/actions/download-files
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Extract Assets
        uses: ./.github/actions/extract-assets
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Extract Images
        uses: ./.github/actions/extract-images
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Resize Images
        uses: ./.github/actions/resize-images
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Update Spritesheets
        uses: ./.github/actions/update-spritesheets
        with:
          working-directory: ${{ env.GITHUB_WORKSPACE }}

      - name: Commit changes
        run: |
          git config --global user.name 'Jon Senchyna'
          git config --global user.email 'TheSench@users.noreply.github.com'
          git commit -am "Auto-update of Spellstone Images"
          git push